import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Xoje Developer</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        algo por dioooss
        {/* <div className={styles.container}>
                    <div>
                        <span>With default Theme:</span>
                    </div>
                    <Switch {...label} defaultChecked/>
                    <Switch {...label} />
                    <Switch {...label} disabled defaultChecked/>
                </div> */}
      </main>
    </>
  )
}
