import Head from 'next/head'
import GalleryProjects from '../components/organisms/GalleryProjects'

export default function Home () {
  return (
    <>
      <Head>
        <title>Xoje Developer</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* Navbar */}
        {/* About */}
        <GalleryProjects />
        {/* Project List */}
        {/* Contact */}
        {/* Footer */}
      </main>
    </>
  )
}
